### ISSUE TITLE
Revdep failure

### ISSUE THREAD

**Issue by rsbivand** [ropensci/unifir#12]
[testthat.Rout.zip](https://github.com/ropensci/unifir/files/10092027/testthat.Rout.zip)
[00check.log](https://github.com/ropensci/unifir/files/10092059/00check.log)

The test seems to pass (Fedora 37, GDAL 3.6.0, **sf** and **terra** development versions if you do not set the row.name in line 11 of test-associate_coordinates.R.

**Comment by mikemahoney218** [comment]
Thank you! Missed this originally, sorry. Will get to CRAN ASAP.

**Comment by rsbivand** [comment]
With current HEAD passes for me now:
[00check.log](https://github.com/ropensci/unifir/files/10145982/00check.log)

**Comment by mikemahoney218** [comment]
Fantastic! Now on CRAN. Thanks for letting me know!
